In [1]:
import numpy as np

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
l=range(5)
l

range(0, 5)

In [8]:
l[0]

0

In [9]:
l[1]

1

In [15]:
# staring number include but not last
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# in this 3 number shows the step count
np.arange(3,16,4)

array([ 3,  7, 11, 15])

In [27]:
# this is linear space first number is staring ,second number is ending and third number generate the linear space between staring and ending point
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
b

array([[5, 6],
       [7, 8]])

In [32]:
a+b

array([[ 6,  8],
       [10, 12]])

In [33]:
a*b

array([[ 5, 12],
       [21, 32]])

In [34]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [35]:
a.dot(b)

array([[19, 22],
       [43, 50]])