In [14]:
import numpy as np

In [15]:
# declare array
a =np.array([5,6,7])

In [16]:
# Print array
print(a[0])

5


In [17]:
# Dimension of array
a.ndim

1

In [18]:
# Dimension of array
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [19]:
# byte size of element
a.itemsize

8

In [20]:
a.dtype

dtype('int64')

In [31]:
# change datatype
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [33]:
a.dtype

dtype('float64')

In [34]:
a.itemsize

8

In [35]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [38]:
# size of array(no of elements)
a.size

6

In [41]:
# shape represnts the information of dimenions(rows*column)
a.shape

(3, 2)

In [43]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [47]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [49]:
a=np.array(([1,2],[3,4],[5,6]))

In [50]:
a.shape

(3, 2)

In [56]:
 # used for reshape the array
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [59]:
# reavel is used to make one dimensional 
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [68]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
# print minimum array
print(a.min())

1


In [70]:
# print maximum array
print(a.max())

6


In [71]:
# sum of all number
print(a.sum())

21


In [76]:
# sum using axis(axis 0 is sum of colummn)
print(a.sum(axis=0))
# (1+3+5 2+4+6)

[ 9 12]


In [77]:
# sum using axis (axis 1 is sum of colummn)
print(a.sum(axis=1))
# (1+2 3+4 5+6)

[ 3  7 11]


In [79]:
# squareroot
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [81]:
 # standard deviation
print(np.std(a))

1.707825127659933
